"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase"; // Ensure this path points to your initialized client

export default function Signup() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{
    type: "success" | "error" | null;
    text: string;
  }>({
    type: null,
    text: "",
  });

  const handleSignup = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setMessage({ type: null, text: "" });

    const formData = new FormData(e.currentTarget);
    const email = formData.get("email") as string;
    const password = formData.get("password") as string;
    const role = formData.get("role") as string;

    // 1. Sign the user up securely using Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      setMessage({ type: "error", text: authError.message });
      setLoading(false);
      return;
    }

    // 2. If Auth is successful, insert the details into your custom 'users' table
    if (authData.user) {
      const { error: dbError } = await supabase.from("users").insert([
        {
          id: authData.user.id, // We use the secure UUID generated by Supabase Auth
          email: email,
          password: password,
          role: role,
          // 'created_at' will be generated automatically by Supabase (timestamptz)
        },
      ]);

      if (dbError) {
        setMessage({ type: "error", text: dbError.message });
      } else {
        setMessage({
          type: "success",
          text: "Account created successfully! Redirecting...",
        });
        // Redirect to the dashboard after a short delay
        setTimeout(() => {
          router.push("/dashboard");
        }, 1500);
      }
    }

    setLoading(false);
  };

  return (
    <div className="min-h-screen flex bg-secondary-light">
      {/* Left Side - Image Area */}
      <div className="hidden lg:block lg:w-1/2 relative bg-primary">
        <img
          src="https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80"
          alt="Campus"
          className="absolute inset-0 w-full h-full object-cover"
        />
        {/* Overlay to ensure text readability */}
        <div className="absolute inset-0 bg-black/40 mix-blend-multiply" />
        
        {/* Descriptive Text over the image */}
        <div className="absolute inset-0 flex flex-col items-center justify-center text-white p-12 text-center">
          <h1 className="text-5xl font-bold mb-4 drop-shadow-lg">N-HELP Portal</h1>
          <p className="text-xl max-w-md drop-shadow-md">
            Join your campus community to seamlessly manage, track, and resolve service requests.
          </p>
        </div>
      </div>

      {/* Right Side - Form */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-4 sm:p-8">
        <div className="max-w-md w-full bg-white rounded-2xl shadow-xl border-t-4 border-primary p-8">
          <h2 className="text-2xl font-bold mb-2 text-secondary text-center">
          Create an Account
        </h2>
        <p className="text-center text-gray-500 mb-6">Join N-HELP</p>

        {message.type && (
          <div
            className={`p-4 mb-6 rounded-lg text-sm ${message.type === "success" ? "bg-primary-light text-primary border border-primary-light" : "bg-red-50 text-red-700 border border-red-100"}`}
          >
            {message.text}
          </div>
        )}

        <form onSubmit={handleSignup} className="space-y-4">
          <div>
            <label
              htmlFor="email"
              className="block text-sm font-medium text-secondary mb-1"
            >
              Email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              required
              className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent transition text-gray-900 bg-white"
              placeholder="you@university.edu"
            />
          </div>

          <div>
            <label
              htmlFor="password"
              className="block text-sm font-medium text-secondary mb-1"
            >
              Password
            </label>
            <input
              type="password"
              id="password"
              name="password"
              required
              minLength={6}
              className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent transition text-gray-900 bg-white"
              placeholder="••••••••"
            />
          </div>

          <div>
            <label
              htmlFor="role"
              className="block text-sm font-medium text-secondary mb-1"
            >
              Account Role
            </label>
            {/* Here is your exact requested dropdown! */}
            <select
              id="role"
              name="role"
              required
              defaultValue="" // <-- Add this here!
              className="w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent transition text-gray-900 bg-white"
            >
              {/* Remove 'selected' from here! */}
              <option value="" disabled>
                Select a role...
              </option>
              <option value="student">Student</option>
              <option value="staff">Staff</option>
            </select>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 px-4 mt-6 bg-primary hover:bg-primary-hover text-white font-semibold rounded-lg transition duration-200 disabled:opacity-50"
          >
            {loading ? "Creating Account..." : "Sign Up"}
          </button>
        </form>
      </div>
    </div>
    </div>
  );
}
