"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../lib/supabase"; // Ensure this path points to your initialized client

export default function Signup() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{ type: "success" | "error" | null; text: string }>({
    type: null,
    text: "",
  });

  const handleSignup = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setMessage({ type: null, text: "" });

    const formData = new FormData(e.currentTarget);
    const email = formData.get("email") as string;
    const password = formData.get("password") as string;
    const role = formData.get("role") as string;

    // 1. Sign the user up securely using Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email,
      password,
    });

    if (authError) {
      setMessage({ type: "error", text: authError.message });
      setLoading(false);
      return;
    }

    // 2. If Auth is successful, insert the details into your custom 'users' table
    if (authData.user) {
      const { error: dbError } = await supabase
        .from("users")
        .insert([
          {
            id: authData.user.id, // We use the secure UUID generated by Supabase Auth
            email: email,
            password: password,
            role: role,
            // 'created_at' will be generated automatically by Supabase (timestamptz)
          }
        ]);

      if (dbError) {
        setMessage({ type: "error", text: dbError.message });
      } else {
        setMessage({ type: "success", text: "Account created successfully! Redirecting..." });
        // Redirect to the dashboard after a short delay
        setTimeout(() => {
          router.push("/dashboard");
        }, 1500);
      }
    }

    setLoading(false);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <div className="max-w-md w-full bg-white rounded-xl shadow-md border border-gray-100 p-8">
        <h2 className="text-2xl font-bold mb-6 text-gray-900 text-center">Create an Account</h2>

        {message.type && (
          <div className={`p-4 mb-6 rounded-md text-sm ${message.type === "success" ? "bg-green-50 text-green-700 border border-green-200" : "bg-red-50 text-red-700 border border-red-200"}`}>
            {message.text}
          </div>
        )}

        <form onSubmit={handleSignup} className="space-y-4">
          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">Email</label>
            <input
              type="email"
              id="email"
              name="email"
              required
              className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="you@university.edu"
            />
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              required
              minLength={6}
              className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="••••••••"
            />
          </div>

          <div>
            <label htmlFor="role" className="block text-sm font-medium text-gray-700 mb-1">Account Role</label>
            {/* Here is your exact requested dropdown! */}
            <select
              id="role"
              name="role"
              required
              defaultValue="" // <-- Add this here!
              className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 bg-white"
            >
              {/* Remove 'selected' from here! */}
              <option value="" disabled>Select a role...</option>
              <option value="student">Student</option>
              <option value="staff">Staff</option>
            </select>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2 px-4 mt-4 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-md transition duration-200 disabled:opacity-50"
          >
            {loading ? "Creating Account..." : "Sign Up"}
          </button>
        </form>
      </div>
    </div>
  );
}